Default: &defaults
  database: todo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: todo_test.sqlite3
  <<: *defaults

Staging:
  database: todo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: todo_production.sqlite3
  poolsize: 100
  <<: *defaults
